// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://japjgvbuvymakqxefxbu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImphcGpndmJ1dnltYWtxeGVmeGJ1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzU2NTU0OTYsImV4cCI6MjA1MTIzMTQ5Nn0.ieHkZ7LEXOI_rz9MS69T5r7xn8v9y5v_GiYZVB0cRlk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);